export enum TableActionEnum {
  PRINT = 'print',
  DOWNLOAD_PDF = 'downloadPDF',
  DOWNLOAD_XLSX = 'downloadXLSX',
  DOWNLOAD = 'download',
  EDIT = 'edit',
  ORDER_CARD = 'orderCard',
  SEND_TO_EMAIL = 'sentToEmail',
  DELETE = 'delete',
  SIGN = 'sign',
  SIGN_AND_SEND = 'signAndSend',
  TRANSACTION_TO_CONTRACTOR_BY_ID = 'transactionToContractorById',
  TRANSFER_TO_TJ = 'transferToTJ',
  REPEAT_PAYMENT = 'repeatPayment',
  REVOKE_SIGN = 'revokeSign',
  SELECTED_DATA = 'selectedData',
  DOWNLOAD_CERTIFICATE = 'downloadCertificate',
  REISSUE = 'reissue',
}
