export enum TableFieldTypes {
  TEXT = 'text',
  DATE = 'date',
  IMG = 'img',
  DOWNLOAD = 'download',
  DATETIME = 'datetime',
  TIME = 'time',
  STATUS = 'status',
  EDIT = 'edit',
  INDICATOR = 'indicator',
  STATUS_INDICATOR = 'status-indicator',
  MULTIPLE_VALUE = 'multiple-value',
  NUMBER = 'number',
  SELECT = 'select',
  DELETE = 'delete',
  TOOLTIP_SHOW = 'tooltip-show',
  LIST = 'list',
  LINK = 'link',
  CONFIRM = 'confirm',
  RATING = 'rating',
}
export enum TableRowActionEnum {
  EDIT = 'edit',
  DELETE = 'delete',
  REFUND = 'refund',
  PRINT = 'print',
  CHANGE_STATUS = 'change-status',
  CHANGE_SHIFT = 'change-shift',
  CONFIRM = 'confirm',
}
