import { ICaption } from '@core/interfaces/table1.interface';
import { MatchMode } from '@core/enums/match-mode.enum';

export class OrderConstants {
  static readonly ORDER_COLUMNS: ICaption[] = [
    {
      key: 'Статус',
      field: 'orderStatusName',
      type: 'text',
      filterType: 'text',
      isFiltered: false,
      isSelected: true,
      width: '155px',
    },
    {
      key: 'Тип заказа',
      field: 'orderTypeName',
      type: 'text',
      filterType: 'text',
      isSelected: true,
      isSortable: true,
      isFiltered: true,
      width: '155px',
    },
    {
      key: 'Создан',
      field: 'createdAt',
      type: 'datetime',
      filterType: 'date',
      mode: MatchMode.equalsOnly,
      isSelected: true,
      width: '155px',
    },
    {
      key: 'Точка',
      field: 'merchantName',
      type: 'text',
      filterType: 'text',
      isSelected: true,
    },
    {
      key: 'Касса',
      field: 'posName',
      type: 'text',
      filterType: 'text',
      isSelected: true,
    },
    {
      key: 'Сумма заказа',
      field: 'orderAmount',
      type: 'number',
      filterType: 'number',
      mode: MatchMode.equalsOnly,
      isSelected: true,
      width: '155px',
    },
    {
      key: 'Сумма оплаты',
      field: 'paymentAmount',
      type: 'number',
      filterType: 'number',
      mode: MatchMode.equalsOnly,
      isSelected: true,
      width: '155px',
    },
    {
      key: 'ID заказа',
      field: 'orderId',
      type: 'text',
      filterType: 'text',
      mode: MatchMode.equalsOnly,
      isSelected: true,
      width: '155px',
    },
    {
      key: 'Внешний номер заказа',
      field: 'invoiceId',
      type: 'text',
      filterType: 'text',
      isSelected: true,
      width: '200px',
    },
    {
      key: 'Номер квитанции',
      field: 'paymentNumber',
      type: 'text',
      filterType: 'number',
      mode: MatchMode.equalsOnly,
      isSelected: true,
      width: '155px',
    },
    {
      key: 'Описание',
      field: 'description',
      type: 'text',
      filterType: 'text',
      isSelected: true,
      width: '200px',
    },
  ];
}
